name: Bug Report 🔥
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to improve this repository!
  - type: dropdown
    id: dropdown_ml
    attributes:
      label: Title
      description: Title
      options:
        - "Call of Duty: Vanguard"
        - "Call of Duty: Black Ops Cold war"
        - "Call of Duty: Modern warfare 2019"
        - "Call of Duty: Black Ops 4"
        - "Call of Duty: Infinite Warfare"
        - "Call of Duty: WWII"
        - "Call of Duty: Black Ops 3"
        - "Other/Multiple (write it/them in the next field)"
        - "None"
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Custom title
      description: Custom title
      placeholder: "Call of Duty: Modern Warfare 2022"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Description of the issue
      description: Small description of the issue
      placeholder: |
        my problem is...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Excepted behavior
      description: What was the excepted behavior?
      placeholder: |
        I was excepting...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Obtained behavior
      description: What is the obtained behavior?
      placeholder: |
        ...but this happened
    validations:
      required: false
  - type: textarea
    attributes:
      label: How to reproduce
      description: How to reproduce?
      placeholder: |
        - step 1: that
        - step 2: this
        - step 3: something
        - ...
    validations:
      required: false
  - type: dropdown
    id: dropdown_id
    attributes:
      label: Do I want to contribute to fix it?
      description: Do I want to contribute to fix it?
      options:
        - "Yes"
        - "No"
        - "Maybe"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Something else?
      description: Something else to inform us?
    validations:
      required: false
